{
 "title": "GitHub Copilot Usage",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Copilot Usage",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "github_org_copilot_billing{metric_name=\"seat_breakdown_active_this_cycle\"}",
     "legendFormat": "Active Users"
    },
    {
     "expr": "github_org_copilot_billing{metric_name=\"seat_breakdown_added_this_cycle\"}",
     "legendFormat": "Added Users"
    },
    {
     "expr": "github_org_copilot_billing{metric_name=\"seat_breakdown_inactive_this_cycle\"}",
     "legendFormat": "Inactive Users"
    },
    {
     "expr": "github_org_copilot_billing{metric_name=\"seat_breakdown_total\"}",
     "legendFormat": "License consumed"
    }
   ]
  },
  {
   "title": "IDE Distribution",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 5, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(github_enterprise_copilot_usage{metric_name=~\".+jetbrains_active_users\"})",
     "legendFormat": "Jetbrains"
    },
    {
     "expr": "sum(github_enterprise_copilot_usage{metric_name=~\".+vscode_active_users\"})",
     "legendFormat": "VSCODE"
    },
    {
     "expr": "sum(github_enterprise_copilot_usage{metric_name=~\".+visual_studio_active_users\"})",
     "legendFormat": "Visual Studio"
    }
   ]
  },
  {
   "title": "Average Active users past 28 days",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "github_org_copilot_billing{metric_name=\"seat_breakdown_active_this_cycle\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average inactive users past 28 days",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "github_org_copilot_billing{metric_name=\"seat_breakdown_inactive_this_cycle\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lines Suggested vs. accepted",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(avg_over_time(github_enterprise_copilot_usage{metric_name=~\".+lines_suggested\"}[$__interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(avg_over_time(github_enterprise_copilot_usage{metric_name=~\".+lines_accepted\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Users over Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 7 },
   "targets": [
    {
     "expr": "github_org_copilot_billing{metric_name=~\"seat_breakdown_active_this_cycle\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "github_org_copilot_billing{metric_name=\"seat_breakdown_inactive_this_cycle\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Visual Stuido Languages",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 7 },
   "targets": [
    {
     "expr": "github_enterprise_copilot_usage{metric_name=~\".+visual_studio_active_users\"}",
     "legendFormat": "{{metric_name}}"
    }
   ]
  },
  {
   "title": "Jetbrains Languages",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "github_enterprise_copilot_usage{metric_name=~\".+jetbrains_active_users\"}",
     "legendFormat": "{{metric_name}}"
    }
   ]
  },
  {
   "title": "VSCode Languages",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "github_enterprise_copilot_usage{metric_name=~\".+vscode_active_users\"}",
     "legendFormat": "{{metric_name}}"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "type": "text",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 20 },
   "options": {
    "content": "<a href='https://postimg.cc/RqMjcw10' target='_blank'><img src='https://i.postimg.cc/HW5d12Vb/dalle.png' border='0' alt='dalle'/></a>"
   }
  }
 ]
}